name: Publish on Itch

on: push

env:
  ITCH_USERNAME: joegamz
  ITCH_GAME_ID: puffle-roundup-minigame

jobs:
  deploy:
    name: Upload to Itch
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install Node.js and dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Specify the version of Node.js you need
      - name: Install Dependencies
        run: npm install

      # Step 3: Build your Phaser game
      - name: Build Game
        run: webpack --config webpack/prod.js

      # Step 5: Upload to Itch.io using itch-publish action
      - uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: ./dist
          itchUsername: ${{env.ITCH_USERNAME}}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildChannel: web
